version: '3'

services:

  mysql-server:
    image: mysql
#    volumes:
#      - ./tmpData:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: siemanejro
    ports:
      - "8001:3306"

  spring-boot:
    build: .
    image: nazkord/siemanejro:0.1
    depends_on:
      - mysql-server
    restart: unless-stopped
    environment:
      DATABASE_HOST: mysql-server
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: siemanejro
      DATABASE_PORT: 3306
    ports:
      - "8080:8080"
